version: 2.1
orbs:
  datacamp-ecr: datacamp/ecr@0
  datacamp-deploy: datacamp/deploy@1
workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - datacamp-ecr/build_and_push_image_to_ecr:
          name: build
          context: org-global
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          account-url: $STAGING_ECR_URL
          extra-docker-args: "--build-arg NPM_TOKEN=${NPM_TOKEN}"

      - datacamp-deploy/deploy: # Staging
          name: deploy-staging
          context: org-global
          new-deploy-opt-in: true
          deploy-url: $STAGING_LAMBDA_DEPLOY_URL
          deploy-password: $STAGING_LAMBDA_DEPLOY_PASSWORD
          requires:
            - build
          filters:
            branches:
              only:
                - master

      - datacamp-ecr/pull_push_to_account:
          context: org-global
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/

      - datacamp-deploy/deploy: # Production
          name: deploy-production
          context: org-global
          new-deploy-opt-in: true
          deploy-url: $PROD_LAMBDA_DEPLOY_URL
          deploy-password: $PROD_LAMBDA_DEPLOY_PASSWORD
          requires:
            - datacamp-ecr/pull_push_to_account
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/