version: 2.1
orbs:
  datacamp-ecr: datacamp/ecr@1
  datacamp-deploy: datacamp/deploy@2
workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - datacamp-ecr/build_and_push_image_to_ecr:
          name: build
          context: org-global
          aws-access-key-id: $OPS_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $OPS_AWS_SECRET_ACCESS_KEY
          account-url: $OPS_ECR_URL
          puller-account-ids: '["301258414863", "487088987264"]'
          extra-docker-args: "--build-arg NPM_TOKEN=${NPM_TOKEN}"

      - datacamp-deploy/deploy: # Staging
          name: deploy-staging
          context: org-global
          requires:
            - build
          filters:
            branches:
              only:
                - master
          # parameters
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          environment: staging

      - datacamp-deploy/deploy: # Production
          name: deploy-production
          context: org-global
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
          # parameters
          aws-access-key-id: $PROD_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $PROD_AWS_SECRET_ACCESS_KEY
          environment: prod
